apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmobility.eclipse.org
  namespace: foundation-internal-webdev-apps
spec:
  selector:
    matchLabels:
      app: openmobility.eclipse.org
      environment: production
  replicas: 2
  template:
    metadata:
      labels:
        app: openmobility.eclipse.org
        environment: production
    spec:
      containers:
      - name: nginx
        image: eclipsefdn/openmobility.eclipse.org
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: openmobility-eclipse-org
  namespace: foundation-internal-webdev-apps
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: openmobility.eclipse.org
    environment: production
---
apiVersion: "route.openshift.io/v1"
kind: "Route"
metadata:
  name: openmobility.eclipse.org
  namespace: foundation-internal-webdev-apps
  annotations:
    haproxy.router.openshift.io/timeout: 20s
spec:
  host: "openmobility.eclipse.org"
  path: "/"
  port:
    targetPort: "http"
  tls:
    insecureEdgeTerminationPolicy: "Redirect"
    termination: "edge"
  to:
    kind: "Service"
    name: openmobility-eclipse-org
    weight: 100